services:
  pg:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
      - PGDATA=/pgdata
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/pgdata:rw
